### ISSUE TITLE
BUG: eval throws error on var (replace eval)

### ISSUE THREAD

**Issue by alexn-s** [SamLewis0602/obsidian-custom-js#17]
@SamLewis0602

i am using typescript and wanted to use the transpiled js files with your awesome plugin, but noticed that the ts output

```
var CoolStringer = class {
  coolify(s) {
    return `\u{1F60E} ${s} \u{1F60E}`;
  }
};
```

does not work.

On the other hand, "regular" js classes work.
```
class CoolStringer {
  coolify(s) {
    return `\u{1F60E} ${s} \u{1F60E}`;
  }
};
```

Basically, whenever there is a var, the files does not get loaded.

Error message from Obsidian Dev Console:
```
main.ts:65 SyntaxError: Unexpected token 'var'
```

**Comment by alexn-s** [comment]
also, eval should probably not be used. i propose using a npm module with better & safer evaluation

**Comment by alexn-s** [comment]
would love to hear your feedback and to merge.
furthermore, i like to work on this extension with you if you would like and grant me dev access to manage this repo together 🙂.

**Comment by SamLewis0602** [comment]
Hi @alexn-s thanks for the PR. I'm happy to look at PRs but I won't be granting you access to manage the repo.

See here for why `eval` is required to work on Obsidian mobile: https://github.com/SamLewis0602/obsidian-custom-js/issues/3#issuecomment-912801366

What OSes have you tested your PR on?

**Comment by alexn-s** [comment]
@SamLewis0602  ok understandable.

OS -> windows, but code is expected to be platform independent.
i think i will probably for your repo, to put my own "spin" on it and drop mobile support,
or would you be willing to create an obsidian-custom-js-desktop repo with features that do not work on mobile,
so that #3 could be solved in an "easier" way?

may i suggest a few ideas for this repo (would love to send pull request for them also)?
of course the suggestions are opinionated, so let know what do you think

1. refactor code and put into src folder (maintainability for the future for creating multiple small files)
2. tsconfig use paths so relative imports dont have to be used (easier to digest)
3. quicker bundler (looking at esbuild/ tsup)
4. types into types/ @types folder

looking forward to your input and hearing about the pr

**Comment by SamLewis0602** [comment]
Rather than creating a plugin for that, you can just `require()` files directly in code blocks in Obsidian if you don't care about mobile support. This plugin only exists because that doesn't work on mobile. So a plugin for desktop-only would be unnecessary. If you do decide to create it, all I ask is that you call it something else to avoid confusion.

For your suggestions, I agree those things are useful in a large javascript project such as a web app, but I don't believe they're necessary (or even applicable in the case of 4) for this small plugin that's basically feature complete as it is.
