### ISSUE TITLE
Can't get plugin to work...

### ISSUE THREAD

**Issue by raelb** [SamLewis0602/obsidian-custom-js#21]
Hi,
I can't seem to get the plugin to work. Not sure what is wrong/missing from my setup?

![image](https://user-images.githubusercontent.com/13108198/148657951-9be41c33-a867-4143-91e8-0deff0000983.png)

![image](https://user-images.githubusercontent.com/13108198/148657966-55be1c16-ce69-40e6-b8d5-a74f5eccd488.png)

![image](https://user-images.githubusercontent.com/13108198/148657984-60a25e10-eeba-405e-bc47-cd37872266a6.png)

![image](https://user-images.githubusercontent.com/13108198/148657994-43f9ccee-7317-4d30-acd9-b54dc2dc020b.png)

![image](https://user-images.githubusercontent.com/13108198/148658000-00896a55-9517-4c9c-aa46-33042a48b55a.png)

**Comment by SamLewis0602** [comment]
First, clear your individual files settings. See https://github.com/SamLewis0602/obsidian-custom-js/issues/10#issuecomment-955249535 for why.

If it still doesn't work after that, it could be due to the backslash you used in your path. Try swapping it for `/` and see if that does the trick.

**Comment by raelb** [comment]
It wasn't due to filling both fields - I had tried that before.
However it was caused by the backslash. Thanks for pointing that out.
You may want to make a mention of that in the readme :). Something that Windows users may fall prey to.

**Comment by SamLewis0602** [comment]
Appreciate you following up - I'll take a note to add it!

**Comment by metawops** [comment]
I still can't get it to work.
First I naturally tried to put the `scripts` folder inside the `.obsidian` folder of my vault. After a bit of reading here in the (closed) issues I learned that the folder for the scripts must not be inside the `.obsidian` folder because this will break compatibility with iOS and Android. => You should put a note about that into your readme. 😉 
Then I put the `scripts` folder directly in my vault folder. Which is a bit annoying because Obsidian's file explorer now shows this folder but it's apparently empty because the file explorer doesn't see `.js` files. 😞 
However, in the CustomJS's settings the first text field ("Individual files") is empty and the folder setting is set to `scripts` (which is the name of the folder inside my vault). => Same error with the dataviewJS example @raelb reported.
Then I tried `/scripts`, `scripts/` and `/scripts/` – none worked (note: no backslashes, only forward slashes used). 🤷‍♂️ 
Switching off the CustomJS plugin and back on again or restarting Obsidian didn't work either.
Any idea?

**Comment by metawops** [comment]
Ohkay ... After a bit more of struggling with this I got it to work. ✅ 
It would have been great if the readme would have said:
- The folder has to be inside your vault directly. Putting it inside your `.obsidian` folder won't work.
- In the settings in the field for the folder don't put any slashes in front or at the end of the folder name (if you have just one folder inside your vault's folder and no subfolders). If you have a subfolder write `scripts/subfolder`(e.g.) with one forward slash in the middle and still no leading or trailing forward slashes.
- Restart Obsidian after you entered a folder in the settings to make things work.
😉

**Comment by willtree8** [comment]
Heya, also having some trouble getting this to work - have tried the advice above and in the other issues but no luck.

I've got `coolString.js` in a `scripts` folder in my main vault directory, in my settings, I'm listing just the folder in that field as `scripts`, no slashes, nothing else. I've also tried having the script in the vault directory and putting `coolString.js` in the individual file box but no luck there either. I'm restarting Obsidian between runs but that doesn't seem to make a difference. All the same error as above :)
I am on linux if that is making any difference.

Thanks in advance!
