### ISSUE TITLE
[Feat] Use nodejs require to load file

### ISSUE THREAD

**Issue by meskill** [SamLewis0602/obsidian-custom-js#3]
Sorry, I'm not familiar with obsidian api, so maybe I do not know something

But can we use `require` function to load scripts over `eval` of a single class? It will allow to use any js-code in scripts not only single class

**Comment by nkoder** [comment]
I would love such approach! I imagine we only have to define a folder which contains scripts in it and in its subfolders etc., where scripts `export {abc};` stuff or `module.exports = {abc};` them, then `const {abc} from customJS;` on the callee side.

It wold be great to not have those constraints that (1) you need to define a class and (2) it has to be the only one in a file.

**Comment by SamLewis0602** [comment]
I agree that would be much better! Unfortunately, we can't do this due to an Obsidian limitation. The reason is that the only way to `require` a file is to use it's full, absolute path — not just the path from the root of the vault. This is accessible on desktop via `this.vault.adapter.basePath` (though it's a private API and could change) but it blows up on mobile.

The other advantage of classes is that your functions can call each other directly inside the class. If you dynamically import individual functions then you'd have to pass the customJS object into them to be able to call other functions.

I believe I exhausted all the options for trying to get it to work with `require()`, but I'd be happy to be proven wrong as that would be a nicer solution. Shoot me a PR if you find something I missed!

**Comment by nkoder** [comment]
thanks for an explanation! ❤️
